/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatementRouteImport } from './routes/statement'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DeliveryNotesRouteImport } from './routes/delivery-notes'
import { Route as CreditNotesRouteImport } from './routes/credit-notes'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'

const StatementRoute = StatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryNotesRoute = DeliveryNotesRouteImport.update({
  id: '/delivery-notes',
  path: '/delivery-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesRoute = CreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-notes': typeof DeliveryNotesRoute
  '/invoices': typeof InvoicesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/statement': typeof StatementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-notes': typeof DeliveryNotesRoute
  '/invoices': typeof InvoicesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/statement': typeof StatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-notes': typeof DeliveryNotesRoute
  '/invoices': typeof InvoicesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/statement': typeof StatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/credit-notes'
    | '/delivery-notes'
    | '/invoices'
    | '/payments'
    | '/products'
    | '/settings'
    | '/statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/credit-notes'
    | '/delivery-notes'
    | '/invoices'
    | '/payments'
    | '/products'
    | '/settings'
    | '/statement'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/credit-notes'
    | '/delivery-notes'
    | '/invoices'
    | '/payments'
    | '/products'
    | '/settings'
    | '/statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  CreditNotesRoute: typeof CreditNotesRoute
  DeliveryNotesRoute: typeof DeliveryNotesRoute
  InvoicesRoute: typeof InvoicesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  StatementRoute: typeof StatementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statement': {
      id: '/statement'
      path: '/statement'
      fullPath: '/statement'
      preLoaderRoute: typeof StatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-notes': {
      id: '/delivery-notes'
      path: '/delivery-notes'
      fullPath: '/delivery-notes'
      preLoaderRoute: typeof DeliveryNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes': {
      id: '/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof CreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  CreditNotesRoute: CreditNotesRoute,
  DeliveryNotesRoute: DeliveryNotesRoute,
  InvoicesRoute: InvoicesRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  StatementRoute: StatementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
